# To install this pre-commit hook, run:
#
# pip install pre-commit (or brew install pre-commit)
# pre-commit install
#
# To run changed files manually: pre-commit
# To run all files manually: pre-commit run --all-files
#
# See also: https://pre-commit.com
default_language_version:
  python: python3.12

exclude: |
  (?x)^(
  app/static/vendor/.*
  )$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.0
    hooks:
      - id: ruff
        args:
          - --config=./pyproject.toml
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-prettier
    # According to mirrors-prettier, prettier 4.0 doesn't support plugins
    # See also: https://github.com/prettier/prettier/issues/15742
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [html, javascript, css, markdown]
        args: [--write]
        additional_dependencies:
          - prettier@3.1.0
          - prettier-plugin-jinja-template@v1.4.1
