# This setup assumes that TLS certificates are handled seperatly, e.g., via nginx
services:
  app:
    build:
      context: .
      target: prod
      dockerfile: Dockerfile
      args:
        - XLWINGS_DEVELOPER_KEY=${XLWINGS_DEVELOPER_KEY-}
    ports:
      - "8000:8000"
    env_file:
      - .env
