import os
from pathlib import Path


def load_dotenv(path) -> None:
    """Minimal .env reader, replacing the python-dotenv dependency.

    The file is generated by create_wasm_settings() in cli.py, so it's always
    plain KEY=value lines with optionally quoted values - no interpolation,
    no `export` prefixes, no multiline values. Missing file is not an error.

    Existing environment variables win, matching python-dotenv's default of
    override=False: the taskpane pushes user-defined env vars into os.environ.
    Within the file, a repeated key resolves to the LAST occurrence - also
    matching python-dotenv, which parses into a dict before applying it.
    """
    try:
        text = Path(path).read_text(encoding="utf-8")
    except OSError:
        return
    values = {}
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        values[key.strip()] = value
    for key, value in values.items():
        os.environ.setdefault(key, value)


load_dotenv(".env")

# xlwings depends on this, so set before importing xlwings
os.environ["XLWINGS_ON_SERVER"] = "true"


def read_bool(env_name: str, default: str = "false") -> bool:
    return os.getenv(env_name, default).lower() == "true"


class Settings:
    enable_examples: bool = read_bool("XLWINGS_ENABLE_EXAMPLES")
    enable_wasm: bool = True
    enable_tests: bool = read_bool("XLWINGS_ENABLE_TESTS")
    environment: str = os.getenv("XLWINGS_ENVIRONMENT", "prod")
    functions_namespace: str = os.getenv("XLWINGS_FUNCTIONS_NAMESPACE", "XLWINGS")
    is_official_lite_addin: bool = read_bool("XLWINGS_IS_OFFICIAL_LITE_ADDIN")


settings = Settings()
