# This is a minimal implementation without support for Socket.IO/Redis functionality
# such as streaming functions, utils.trigger_script(). To support object handles, you
# will need to configure an external Redis service via `XLWINGS_OBJECT_CACHE_URL`
services:
  app:
    build: &build
      context: ..
      target: prod
      dockerfile: Dockerfile
    restart: always
    ports:
      - "443:8000"
    # Workers can be scaled to whatever meets the traffic
    command: >
       gunicorn app.main:main_app
       --bind 0.0.0.0:8000
       --keyfile /project/certs/privkey.pem
       --certfile /project/certs/fullchain.pem
       --access-logfile -
       --workers 2
       --worker-class uvicorn.workers.UvicornWorker
    volumes:
      - ../certs:/project/certs:ro
    env_file:
      - ../.env
    environment:
      - XLWINGS_ENABLE_SOCKETIO=false
