# Requires fullchain.pem and privkey.pem in the certs folder
services:
  nginx:
    image: nginx:1.27.0
    restart: always
    ports:
      - "443:443"
    volumes:
      - ../nginx/nginx-prod.conf:/etc/nginx/conf.d/default.conf
      - ../certs:/project/certs:ro

  app:
    build: &build
      context: ..
      target: prod
      dockerfile: Dockerfile
    restart: always
    # Workers can be scaled to whatever meets the traffic
    command: >
       gunicorn app.main:main_app
       --bind 0.0.0.0:8000
       --access-logfile -
       --workers 2
       --timeout 30
       --worker-class uvicorn.workers.UvicornWorker
    env_file:
      - ../.env
    environment:
      XLWINGS_SOCKETIO_MESSAGE_QUEUE_URL: redis://redis:6379/0

  socketio:
    build: *build
    restart: always
    # Workers must be exactly 1 as this is a stateful service
    command: >
       gunicorn app.main:sio_app
       --bind 0.0.0.0:8000
       --access-logfile -
       --workers 1
       --worker-class uvicorn.workers.UvicornWorker
    env_file:
      - ../.env
    environment:
      XLWINGS_SOCKETIO_SERVER_APP: true
      XLWINGS_SOCKETIO_MESSAGE_QUEUE_URL: redis://redis:6379/0

  redis:
    # This can be replaced with an external Redis service
    image: redis:7.4.0
    restart: always
