"""File inventory for the Office.js CDN mirror.

The authoritative, hand-curated list of Office.js files (Excel-only subset) that
scripts/mirror_officejs.py downloads from Microsoft's hosted CDN. The mirror
always fetches exactly this list -- it never inspects the existing vendored tree
-- so this file is the single source of truth for what gets vendored.

The list is pruned to only CDN-available files: the discontinued npm package
bundled ~180 locales, but the hosted build ships only the base locales and lets
regional variants (de-at, en-gb, ...) fall back at runtime.

Excluded on purpose (nothing loads them at runtime): `*.debug.js`; `LICENSE.md`
(fetched from the repo instead); and the authoring-only type/IntelliSense files
`office.d.ts` (~8.6M) and `office-vsdoc.js` (~3M) -- editor types come from the
`@types/office-js` dev dependency, not the served static tree.

To adjust what's vendored, edit this list directly. If the CDN adds/removes
files, run a mirror, then reconcile this list against the resulting tree
(re-applying the exclusions above).
"""

OFFICEJS_FILES = [
    "agaveerrorux/agaveerrorux.js",
    "agaveerrorux/images/agavedefaulticon32x32.png",
    "agaveerrorux/images/agavedefaulticon96x96.png",
    "agaveerrorux/images/businessbarclose_16x16x32.png",
    "agaveerrorux/images/dropdownarrow_16x16x32.png",
    "agaveerrorux/images/ellipsis_16x16x32.png",
    "agaveerrorux/images/miniinfoblue_16x16x32.png",
    "agaveerrorux/images/moe_default_icon.png",
    "agaveerrorux/images/moe_status_icons.png",
    "agaveerrorux/images/office.png",
    "agaveerrorux/images/refresh_16x16x32.png",
    "agaveerrorux/index.html",
    "agaveerrorux/style/agaveerrorux.css",
    "am-et/office_strings.js",
    "ar-sa/office_strings.js",
    "ariatelemetry/aria-web-telemetry-2.8.0.min.js",
    "ariatelemetry/aria-web-telemetry-2.9.0.min.js",
    "ariatelemetry/aria-web-telemetry.js",
    "bg-bg/office_strings.js",
    "bn-in/office_strings.js",
    "ca-es/office_strings.js",
    "cs-cz/office_strings.js",
    "custom-functions-runtime.js",
    "cy-gb/office_strings.js",
    "da-dk/office_strings.js",
    "de-de/office_strings.js",
    "el-gr/office_strings.js",
    "en-us/office_strings.js",
    "es-es/office_strings.js",
    "es-mx/office_strings.js",
    "es6-promise.js",
    "et-ee/office_strings.js",
    "eu-es/office_strings.js",
    "excel-15.01.js",
    "excel-15.02.js",
    "excel-15.js",
    "excel-android-16.00.js",
    "excel-ios-16.00.js",
    "excel-mac-16.00-core.js",
    "excel-mac-16.00.js",
    "excel-web-16.00-core.js",
    "excel-web-16.00.js",
    "excel-win32-16.00.js",
    "excel-win32-16.01-core.js",
    "excel-win32-16.01.js",
    "excel-winrt-16.00.js",
    "excelios-15.js",
    "excelwebapp-15.01.js",
    "excelwebapp-15.02.js",
    "excelwebapp-15.js",
    "fa-ir/office_strings.js",
    "fi-fi/office_strings.js",
    "fil-ph/office_strings.js",
    "fr-ca/office_strings.js",
    "fr-fr/office_strings.js",
    "gl-es/office_strings.js",
    "gu-in/office_strings.js",
    "he-il/office_strings.js",
    "hi-in/office_strings.js",
    "hr-hr/office_strings.js",
    "html2canvas.js",
    "hu-hu/office_strings.js",
    "id-id/office_strings.js",
    "is-is/office_strings.js",
    "it-it/office_strings.js",
    "ja-jp/office_strings.js",
    "kk-kz/office_strings.js",
    "kn-in/office_strings.js",
    "ko-kr/office_strings.js",
    "lo-la/office_strings.js",
    "lt-lt/office_strings.js",
    "lv-lv/office_strings.js",
    "ml-in/office_strings.js",
    "mr-in/office_strings.js",
    "ms-my/office_strings.js",
    "nb-no/office_strings.js",
    "nl-nl/office_strings.js",
    "nn-no/office_strings.js",
    "o15apptofilemappingtable.js",
    "office.js",
    "pl-pl/office_strings.js",
    "pt-br/office_strings.js",
    "pt-pt/office_strings.js",
    "ro-ro/office_strings.js",
    "ru-ru/office_strings.js",
    "sk-sk/office_strings.js",
    "sl-si/office_strings.js",
    "sr-cyrl-cs/office_strings.js",
    "sr-cyrl-rs/office_strings.js",
    "sr-latn-cs/office_strings.js",
    "sr-latn-rs/office_strings.js",
    "sv-se/office_strings.js",
    "sw-ke/office_strings.js",
    "ta-in/office_strings.js",
    "te-in/office_strings.js",
    "telemetry/oteljs.js",
    "telemetry/oteljs_agave.js",
    "th-th/office_strings.js",
    "tr-tr/office_strings.js",
    "uk-ua/office_strings.js",
    "ur-pk/office_strings.js",
    "vi-vn/office_strings.js",
    "webauth/webauth.browserauth.js",
    "webauth/webauth.implicit.js",
    "zh-cn/office_strings.js",
    "zh-tw/office_strings.js",
]
